export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRIC_DATA_RECEIVED = "EVENT/METRIC_DATA_RECEIVED";
export const LAST_METRIC_MEASUREMENT = "EVENT/LAST_METRIC_MEASUREMENT";
export const SELECT_LIST_METRICS = "EVENT/SELECT_LIST_METRICS";
export const DEFINE_LIST_METRICS = "EVENT/DEFINE_LIST_METRICS";
